### ISSUE TITLE
Extra newlines in bbcode string when using getWysiwygEditorValue on Firefox

### ISSUE THREAD

**Issue by jetand** [samclarke/SCEditor#401] opened 2015-03-24 08:41 UTC
Hi. We are using version 1.4.6 of Sceditor and we have noticed that when you use Firefox it adds extra newlines that are not visible to the user until the user saves the document and other people read it where the document is rendered. I don't think this is fixed in 1.4.7 according to the posts on sceditor.com.

We have bound a callback function on the editors valuechanged event and we update a character counter after user input. We get the count from getWysiwygEditorValue(). Here's the funny thing: **when I remove this call the extra lines stopped appearing on Firefox**. Please see the screenshots below.

![news_chrome](https://cloud.githubusercontent.com/assets/6572543/6797932/bef6f2a2-d210-11e4-86d1-01c0a7dea198.png)
![news_firefox](https://cloud.githubusercontent.com/assets/6572543/6797935/c31f9e9c-d210-11e4-83d0-d3279240574e.png)

I'll gladly give you additional info on this issue when needed.

**Comment by brunoais** [comment] 2015-03-24 10:12
I wonder if this is related to the extra `<br>` that firefox has. The one it has "bogus" in its name.

**Comment by jetand** [comment] 2015-03-24 10:15
It could be. Here's a screenshot of the DOM in element inspector.
![lines_dom](https://cloud.githubusercontent.com/assets/6572543/6799556/7c62e5b8-d21f-11e4-8326-aa030f55d998.png)

**Comment by jetand** [comment] 2015-03-24 10:43
![animation](https://cloud.githubusercontent.com/assets/6572543/6799999/5ccab06a-d223-11e4-8e08-b051ab00f392.gif)

**Comment by brunoais** [comment] 2015-03-24 12:29
What did you use? `Enter` or `CTRL + Enter?`

**Comment by jetand** [comment] 2015-03-24 12:30
Just Enter.

**Comment by brunoais** [comment] 2015-03-24 13:09
Try using  `CTRL + Enter`

**Comment by jetand** [comment] 2015-03-24 13:24
The problem is that the our users don't know the difference between Enter and Shift+Enter and even if they did there is no visual difference between Shift+Enter and Enter in the editor. Unlike for example in MS Word where you press Enter you clearly get a much greater vertical space between paragraphs than using Shift+Enter. But in Sceditor there is nothing visual to separate a paragrah break and line break. For the end-user line breaks appear to have been doubled when viewed later where the text is rendered. What they see is not what they get.

My point is that calling method getWysiwygEditorValue() should not make any visible changes to the editor object nor should it give back different results in various browsers when given the same user input to the editor.

**Comment by jetand** [comment] 2015-03-24 13:43
People also write stuff in the editor with mobile devices so they can't even use Shift+Enter.

**Comment by brunoais** [comment] 2015-03-24 16:45
Duplicate of: #356 (although much different titles...)

**Closed by brunoais** 2015-03-24 16:45 UTC
