### ISSUE TITLE
[code] tag gets reproduced on every new line

### ISSUE THREAD

**Issue by timint** [samclarke/SCEditor#768] opened 2020-04-06 21:30 UTC
Assuming this project is dead and no one is maintaining it. It will be worth a try at least to report a bug.

When marking text and clicking the code button, then [code] gets printed on every single line rather than the beginning and the end of the block.

    $('textarea[name="message"]').sceditor({
      format: "bbcode",
      plugins: "plaintext",
      pastetext: {
        addButton: true,
        enabled: true,
      },
      style: "/vendor/sceditor/themes/content/default.min.css",
      locale: "en",
      emoticonsEnabled: false,
      enablePasteFiltering: true,
      toolbar: "bold,italic,underline,strike|removeformat|bulletlist,orderedlist,table|code,quote|horizontalrule,image,link,unlink|source",
      bbcodeTrim : true,
      parserOptions: {
        breakBeforeBlock: false,
        breakStartBlock: false
      },
      width: "auto"
    });

![image](https://user-images.githubusercontent.com/359192/78607062-a17ffd00-785e-11ea-9634-fa152c153005.png)

**Comment by brunoais** [comment] 2020-04-07 08:16
Can you reproduce this in the website?

**Comment by timint** [comment] 2020-04-07 12:02
Set up a bbcode example and i will try.
Can you reproduce it with the given code example?

**Comment by timint** [comment] 2020-04-07 12:10
I managed to reproduce it with the following lines of code:

    $('textarea[name="message"]').sceditor({
      format: "bbcode",
      style: "/vendor/sceditor/themes/content/default.min.css",
    });

Using latest 2.1.3.

**Comment by brunoais** [comment] 2020-04-07 19:49
Does it happen with [this one](https://www.sceditor.com/)?

**Comment by timint** [comment] 2020-04-07 21:24
No it does not. And I compared sceditor.min.js and they are exactly alike.
Are you only loading sceditor.min.js?

These are my loaded sources:

    document::$snippets['head_tags']['sceditor'] = '<link rel="stylesheet" href="'. WS_DIR_APP . 'vendor/sceditor/themes/default.min.css" />';

    document::$snippets['foot_tags']['sceditor'] = '<script src="'. WS_DIR_APP . 'vendor/sceditor/jquery.sceditor.bbcode.min.js"></script>' . PHP_EOL
                                                 . '<script src="'. WS_DIR_APP . 'vendor/sceditor/formats/bbcode.js"></script>' . PHP_EOL
                                                 . '<script src="'. WS_DIR_APP . 'vendor/sceditor/plugins/plaintext.js"></script>' . PHP_EOL
                                                 . '<script src="'. WS_DIR_APP . 'vendor/sceditor/languages/'. language::$selected['code'] .'.js"></script>';

**Comment by timint** [comment] 2020-04-07 22:10
It seems to be resolved when using **jquery.sceditor.min.js** instead of **jquery.sceditor.bbcode.min.js**. What is jquery.sceditor.bbcode.min.js used for?

**Comment by brunoais** [comment] 2020-04-08 06:14
`jquery.sceditor.bbcode.min.js` is the equivalent of including both SCEditor and the bbcode editor in a single file.
In practice, the effect was the same as (for your code):

```
document::$snippets['foot_tags']['sceditor'] = '<script src="'. WS_DIR_APP . 'vendor/sceditor/jquery.sceditor.min.js"></script>' . PHP_EOL
                                             . '<script src="'. WS_DIR_APP . 'vendor/sceditor/formats/bbcode.js"></script>' . PHP_EOL
                                             . '<script src="'. WS_DIR_APP . 'vendor/sceditor/formats/bbcode.js"></script>' . PHP_EOL
```

**Comment by timint** [comment] 2020-04-08 15:19
That makes sense, I'm happy we got it working. :) Thank you @brunoais 
If others also are confused by jquery.sceditor.bbcode.min.js I think tossing it completely is an idea.
Cheers

**Comment by brunoais** [comment] 2020-04-08 20:30
I'll leave that to @samclarke. He's the owner-

**Comment by timint** [comment] 2020-04-08 20:43
Have you heard from the man? He was seen last active may 2018.

**Comment by timint** [comment] 2020-04-09 12:24
The problem persists. Can you confirm it here?
Using latest Chrome.
https://jsfiddle.net/hy3bz68t/1/

**Comment by brunoais** [comment] 2020-04-09 19:22
I can't reproduce. Use a screen recorder, please

**Comment by timint** [comment] 2020-04-09 19:26
Simply copy paste the code from the left into the editor. Select all content and click the code button.
I will be back with a screen recording.

**Comment by timint** [comment] 2020-04-09 20:18
Here is your video https://easyupload.io/8jpxy9
Clean install, clean new browser, happens in any browser.
Using the official sources seen in the link. https://jsfiddle.net/hy3bz68t/1/

**Comment by brunoais** [comment] 2020-04-09 21:37
Like this?
![cannot_reproduce](https://user-images.githubusercontent.com/639467/78942956-ac32d000-7ab2-11ea-8219-c9c25d6e7af8.gif)

**Comment by timint** [comment] 2020-04-09 21:50
Here goes new computer, Windows 10 and latest Chrome.

![2020-04-09-23-48-37](https://user-images.githubusercontent.com/359192/78943731-af32be00-7abc-11ea-8b5e-3b07bb59d452.gif)

2nd attempt and so on can turn out fine. But I 9 out 10 times get it wrong when initially marking and select Code. When it come to the forums where this is used. Every user gets it wrong every single time they post code. And it's annoying.

**Comment by timint** [comment] 2020-04-09 22:11
Windows 10 - Firefox newest version.

Worked first two times. Then third time I get this.

![2020-04-10-00-09-13](https://user-images.githubusercontent.com/359192/78945055-ac859800-7abf-11ea-8150-29e9211238b9.gif)

**Comment by timint** [comment] 2020-04-09 22:23
Windows 10 - Opera latest version

First attempt

![2020-04-10-00-21-58](https://user-images.githubusercontent.com/359192/78945778-6b8e8300-7ac1-11ea-8f34-d0eef01d338d.gif)

**Comment by timint** [comment] 2020-04-09 22:29
Latest Chrome again, using minimal sources.

![2020-04-10-00-27-11](https://user-images.githubusercontent.com/359192/78946173-4c442580-7ac2-11ea-9989-a15b025196e6.gif)

https://jsfiddle.net/x3zw6n12/

**Comment by timint** [comment] 2020-04-09 22:34
And lastly a demonstration of how this problem makes no absolute sense to me.
![2020-04-10-00-32-45](https://user-images.githubusercontent.com/359192/78946416-f328c180-7ac2-11ea-8d68-57e948f58824.gif)

**Comment by timint** [comment] 2020-05-01 03:06
@brunoais did you bail on me?

**Comment by brunoais** [comment] 2020-05-01 07:24
@timint No. I just forgot to tag and my busy life came back to me. My company is making me do overtime to handle all the clients..
Can't do any more around now. If someone can help, it can be the one who made the editor. For now, I just wish someone would fork SCE and lead its development while including @samclarke as code editors...

**Comment by timint** [comment] 2020-05-01 18:18
@brunoais :) Agree. Try talking @samclarke into posting a note that the project needs someone to take over. There are not too many alternatives out there for bbcode editors.

**Comment by timint** [comment] 2020-06-24 13:35
@samclarke @samclarke @samclarke 
Wakey pakey @samclarke, sun is shining! 😁

**Comment by woodholly** [comment] 2021-04-24 21:02
I think it is related to this bug. This is probably linked to rich-text-paste:
https://user-images.githubusercontent.com/65503093/115967757-01664600-a53d-11eb-976b-89485d6e8e9b.gif

**Comment by woodholly** [comment] 2021-04-25 13:46
I fixed this, but code editing is generally useless without undo/redo support...

**Comment by samclarke** [comment] 2021-04-25 14:19
It's due to `<div>` tags being pasted inside of a `<p>` tag.

The spec says `<p>` tags are closed by the start of another block element. When the HTML is parsed by the browser using `innerHTML`, the `<p>` tag gets closed and the way everything is then interpreted results in the unexpected output.

For example, parsing:
```html
<p><code><div>line 1<br></div><div>line 2<br></div></code><br></p>
```
with `innerHTML` will result in:

```html
<p><code></code></p><div><code>line 1<br></code></div><div><code>line 2<br></code></div><br><p></p>
```

Which is what gives the strange output. You can try it in the dev console:

```js
let div = document.createElement('div');
div.innerHTML = '<p><code><div>line 1<br></div><div>line 2<br></div></code><br></p>';
console.log(div.innerHTML);
```

I've updated the `fixNesting()` (#820) to handle blocks inside of `<p>` tags which fixes this. It should be fixed in the next release.

**Comment by samclarke** [comment] 2021-04-25 14:59
@woodholly thanks for reporting. That's a different bug to this which should be fixed by #804. If you use the undo plugin that should enable undo/redo.

**Comment by woodholly** [comment] 2021-04-25 15:08
@samclarke I'll try undo plugin, thanks. Code paste should be cleaned from all tags except <br> (already done inside bbcode.js, but were not done in paste code), here is my patch/diff
(to apply: git am < file.patch)
[0001-fixes-paste-into-code-bugs.patch.txt](https://github.com/samclarke/SCEditor/files/6372237/0001-fixes-paste-into-code-bugs.patch.txt)

**Comment by timint** [comment] 2021-04-25 17:20
If I remember right, it's not a rich text problem. Because I copy raw code straight from my code editor into SCEditor. As soon as I select the block and choose code I get the issue randomly. Meaning it sometimes work.

**Comment by samclarke** [comment] 2021-04-25 18:02
It could be your code editor adding a rich text version of your code to the clipboard when copying (it's what VSCode and a few others do). Are you able to reproduce the issue here (build of the `fixNesting()` changes): https://jsfiddle.net/sjmeLrp7/

**Comment by woodholly** [comment] 2021-04-25 18:12
I already fixed that lol.

**Comment by timint** [comment] 2021-04-25 19:43
There is no code editor I am aware of that copies the raw source code in rich text format. What's the point of doing so? To do so you must have used an extension. Pasting your clipboard into Wordpad should reveal if it's rich text. I just tried Notepad++ and Visual Code and it's raw text, no rich text data.

**Comment by woodholly** [comment] 2021-04-25 20:16
@timint, I meant not rich text copy but html, copy any highlighted code from internet and paste it into sceditor code block, and you are done

**Comment by timint** [comment] 2021-04-25 21:01
My response was a reply to @samclarke. I should have pointed that out.

**Closed** 2021-06-25 08:23 UTC
Labels: Bug
