### ISSUE TITLE
Bug when editing 

### ISSUE THREAD

**Issue by Ben-MyBB** [samclarke/SCEditor#563] opened 2017-04-02 12:59 UTC
https://community.mybb.com/thread-209091.html

**Comment by samclarke** [comment] 2017-04-03 13:39
From testing this seems to be specific to Edge (and possibly IE) and is caused by it pasting an `<li>` tag inside an `<li>` tag resulting in `<li>item 1<li>item 2</li></li>`.

**Comment by Simicro** [comment] 2017-04-03 16:11
Hi Sam,

I am the guy who reported the problem through the link provided by Ben-MyBB

I am on Firefox 52.0.2 (64 bits) Windows.

Many thanks for considering to solve this problem or bug.

**Comment by samclarke** [comment] 2021-10-14 13:05
Thanks for reporting, as far as I can tell this is already fixed on the master branch so closing this. If you can still reproduce it please re-open this or create a new issue.

**Closed by samclarke** 2021-10-14 13:05 UTC
Labels: Minor Bug, Cannot Reproduce
