### ISSUE TITLE
Custom BBcode incorrect convert in source mode

### ISSUE THREAD

**Issue by fyllekanin** [samclarke/SCEditor#510] opened 2016-02-28 00:04 UTC
`$.sceditor.plugins.bbcode.bbcode
        .set("imgl", { tags: { imgl: null }, format: "[imgl]{0}[/imgl]", html: '<div class="imgl"><img alt="imgl" style="max-width: 98%; cursor: pointer;" src="{0}" align="left" border="0" alt /></div>' });`

Works in "normal mode" but when going to source mode it get converted to [img]link[/img].

**Comment by cyphix333** [comment] 2016-04-30 14:57
Don't you want?

```javascript
    tags: {
        "div": {
            "class": ["img1"]
        }
    }
```

?

Though not sure how that will work with the `<img>` inside there?

**Comment by samclarke** [comment] 2016-12-08 20:53
Closing as not a bug. The `tags` value needs be as @cyphix333 example to work with the posted HTML.

**Closed by samclarke** 2016-12-08 20:53 UTC
