### ISSUE TITLE
SCEditor Bugs with Windows 10, Browser Edge (EdgeHTML)

### ISSUE THREAD

**Issue by q2apro** [samclarke/SCEditor#501] opened 2016-01-20 17:38 UTC
Hi, I just wanted to report that some of my users have problems using SCEditor with the Edge browser. Since I don't have Windows 10 I cannot test it. 

Maybe some of you has got the chance?

Reported: 
1. Content was lost entirely when submitting. 
2. When hitting Enter key the cursor jumps to the beginning of the line instead to the next line.
3. No paragraphs are added (all in one line). Relates to 2.

**Comment by jetand** [comment] 2016-01-21 06:49
Our clients have also encountered item 2, that the enter key does not to make a new paragraph. It does but it does not move the cursor there. Workaround has been to tell Edge users to use Shift+Enter. Here's my report from earlier https://github.com/samclarke/SCEditor/issues/477

**Comment by q2apro** [comment] 2016-01-23 14:28
Important: Instead of *HTML-Rendering-Engine Trident* the browser [Edge](https://en.wikipedia.org/wiki/Microsoft_Edge#EdgeHTML) uses [EdgeHTML](https://en.wikipedia.org/wiki/EdgeHTML) which is probably the source of the problem.

**Comment by q2apro** [comment] 2016-01-23 14:33
More findings:

- TinyMCE seems also to have issues: https://github.com/tinymce/tinymce/issues/2610
- CKEditor crashes: http://stackoverflow.com/q/31714690/1066234

I think we should file a bug report to Microsoft like CKEditor team did it: https://connect.microsoft.com/IE/feedback/details/1577449/edge-browser-crashes-when-using-ckeditor-toggling-from-wysiwyg-to-source-mode

But my problem is I cannot test since I have no Win 10 or Edge.

**Comment by brunoais** [comment] 2016-03-29 21:28
I tested this and check how it works.
It is actually a problem with Edge. Let's see how MS acts on it.

**Comment by jankoepke** [comment] 2016-09-22 10:18
Microsoft marked the problem as fixed.
The SCEditor still not working in MS Edge.

I hope someone can fixe the issue, cause the editor works realy great with bbcode

**Comment by samclarke** [comment] 2017-01-13 01:24
I've done some testing and I can't reproduce bug 1 so I'm assuming it was a bug in Edge which has been fixed. Bugs 2 & 3 have already been fixed by commit 6cd5db2 so closing this.

**Closed by samclarke** 2017-01-13 01:24 UTC
Labels: Not-a-bug

**Comment by sylvaindurand** [comment] 2018-01-18 22:52
One year later, I also faced the problem number 1: all content was lost when submitting with Edge!
In finally found out that it occurred because of my content security policy header: you need to allow `frame-src 'self'`! 
I hope it will be useful if someone faces the same issue.
