### ISSUE TITLE
bullets does not work in Sceditor

### ISSUE THREAD

**Issue by GouriSancroj** [samclarke/SCEditor#460] opened 2015-07-19 14:27 UTC
Hi,

When I try to paste bullet listed content in sceditor textarea , only content is displaying without bulletlist. Please can anyone help me in this.

Thank you in advance.

**Comment by brunoais** [comment] 2015-07-19 17:54
The textarea only allows text. In order to paste text with formatting, you have to use SCE in WYSIWYG mode.

**Comment by GouriSancroj** [comment] 2015-07-20 03:59
Can you please explain how to use SCE in WYSIWYG mode. Im using sceditor bbcode plugin .

**Comment by brunoais** [comment] 2015-07-20 08:00
The plugin is irrelevant for the WYSIWYG mode.
Just click the "view source" button
E.g. the last one in this [example page](http://www.sceditor.com/), until it appear not selected. When that happens, you are in WYSIWYG mode. The alternative is the source mode (when the button appears selected).

**Comment by GouriSancroj** [comment] 2015-07-20 08:09
Im trying to paste formatted content (contains bullets , styles , background color , tables) in Sceditor , but only content is displaying the styles , bullets which i have given to the content are not displaying

**Comment by brunoais** [comment] 2015-07-20 08:15
Which browser are you using?

**Comment by GouriSancroj** [comment] 2015-07-20 08:16
chrome , mozilla , IE , firefox. Mostly We use chrome.

**Comment by brunoais** [comment] 2015-07-20 09:04
Which mozilla browser besides firefox?

**Comment by GouriSancroj** [comment] 2015-07-20 09:05
Mostly we use chrome and IE

**Comment by brunoais** [comment] 2015-07-20 09:27
Those are not from Mozilla.

Anyway, I can't see to be able to reproduce it here. Please get me a video (or gif image) showing how you are doing it?

**Comment by GouriSancroj** [comment] 2015-07-20 09:34
okay sure . I uploading the image of sceditor and content image. I am trying to paste the content in sceditor. But Bullets are not displaying

![bullets](https://cloud.githubusercontent.com/assets/13404874/8773249/6937b7a6-2ef0-11e5-808a-0dd0b69fa6ed.png)
![content](https://cloud.githubusercontent.com/assets/13404874/8773270/936115b8-2ef0-11e5-9825-9552ac5b6239.png)

**Comment by brunoais** [comment] 2015-07-20 12:32
Sheesh... THose images are huge with so much white...
Anyway, try to copy and paste only the first list. Then try again the 2nd list. See if it works.

**Comment by GouriSancroj** [comment] 2015-07-20 12:44
I have tried like that also , but bullets are not displaying. 
I am using bbcode plugin

**Comment by brunoais** [comment] 2015-07-20 21:15
What if you turn the bbcode plugin off, then?

**Comment by GouriSancroj** [comment] 2015-07-21 04:27
I dint try that . Can you please tell how to off bbcode plugin. If I put of bbcode, plugin how editor will work?

**Comment by brunoais** [comment] 2015-07-21 06:55
Just remove the plugin from the plugins list in the initialization code.

**Comment by GouriSancroj** [comment] 2015-07-21 07:06
Editor is not working at all

**Comment by brunoais** [comment] 2015-07-22 16:42
Are you sure you are removing the plugin only?

**Comment by GouriSancroj** [comment] 2015-07-23 05:16
No Im not removing plugin , I am figuring out how to make all styles along with bullets to display in sceditor . Give me any suggestions . 
Thank you

**Comment by GouriSancroj** [comment] 2015-07-25 15:41
Do we have option to give color to selected text in sceditor

**Comment by OmarHawk** [comment] 2016-12-10 20:16
Regarding lists from MS Word: #346

Seems to be not working out of the box. Back then, I wrote a custom command to enable that which dealt with most of the cases, MS Word produced for lists (e.g. list style types, different list levels, etc., etc.).

**Comment by samclarke** [comment] 2017-03-10 19:22
Closing as issue is caused by Word's strange formatting. Fixing #346 will fix this.

**Closed by samclarke** 2017-03-10 19:22 UTC
Labels: Bug?, Cannot Reproduce, Question
