### ISSUE TITLE
Text editor crashing in IE

### ISSUE THREAD

**Issue by varora1406** [samclarke/SCEditor#576] opened 2017-08-30 05:33 UTC
Hi,

My application only uses jquery.sceditor.bbcode.js file from long time.
Now suddenly, its noticed that while opening editor is crashing IE. After debugging, I found its issue in plugin itself as bbcode doesn't respond timely and maybe gets into deadlock according to me.

![image](https://user-images.githubusercontent.com/24986539/29856792-d0a083ea-8d72-11e7-88c1-33ca88d6b77c.png)

**Comment by varora1406** [comment] 2017-08-30 05:38
![image](https://user-images.githubusercontent.com/24986539/29856939-9a686954-8d73-11e7-9449-ab56c825fdc6.png)

**Comment by varora1406** [comment] 2017-08-30 10:12
3. ![image](https://user-images.githubusercontent.com/24986539/29867551-92173f5c-8d99-11e7-96c6-61680bd28837.png)

1. ![image](https://user-images.githubusercontent.com/24986539/29867579-a8e9be9e-8d99-11e7-801d-060c6923e394.png)

2. ![image](https://user-images.githubusercontent.com/24986539/29867628-c8431c0e-8d99-11e7-8d8b-c0f07f265d19.png)

I hope you got answers to all your questions

**Comment by brunoais** [comment] 2017-08-30 12:06
Update your SCE to the latest version pls

**Comment by varora1406** [comment] 2017-08-30 17:27
The file which i need is jquery.sceditor.bbcode.js only. And I found its latest version from sceditor.com and have shared a block of code as well from that file.
Where can i find more latest version to it?

**Comment by rnilsen75** [comment] 2017-09-06 09:22
@brunoais the latest released, downloadable version does not fix the issue. I see a lot of changes have been committed since then, as it is rather old. But when  to attempt to build the latest code using grunt, I run into issues with rollup:

`Running "rollup:build" (rollup) task
Task source: C:\repos\sceditor\node_modules\grunt-rollup\tasks\rollup.js
options.entry is deprecated, use options.input
The following options have been renamed — please update your config: moduleName -> name, sourceMap -> sourcemap, sourceMapFile -> sourcemapFile, useStrict -> strict
Warning: bundle.generate(...) now returns a Promise instead of a { code, map } object Used --force, continuing.`

Any clues on how to fix this? Regardless, I would really appreciate it if you can create a build for us that we can test on.

**Comment by varora1406** [comment] 2017-09-06 09:58
I have one more question.
I can find jquery.sceditor.bbcode.js in Version 1.5.2 which is latest.
But I can't find same file in this current Github repo itself.
Can you tell me the reason behind this?

**Comment by brunoais** [comment] 2017-09-06 15:58
Only @samclarke can answer that.

**Comment by varora1406** [comment] 2017-09-07 05:52
@brunoais Sam might be busy. We just need a quick help from you. We only need grunt file of jquery.sceditor.bbcode.js **(latest unreleased version 2017)** which is a combination of jquery.sceditor.js and bbcode.js.

![image](https://user-images.githubusercontent.com/24986539/30147946-9a6a88f0-93be-11e7-9536-1ac5ed22ca0b.png)

Image can tell the configuration of same. I am also compiling at my end, but as I am new for this, some minor challenges consuming my time. It would be very good of you @brunoais if you can return me. 👍

**Comment by samclarke** [comment] 2017-09-09 18:34
@rnilsen75 running `grunt build` on the master branch should now work again.

I don't think updating to the current master branch will fix the issue as not much has changed with the BBCode parser. I've tested with the IE 11 VM from MS and everything seems to work fine although that is an older version of IE.

As this the first report I'm guessing it's specific to version 11.540.15063.0 and not all versions of IE 11. I'm running the update on the IE 11 VM now so hopefully I'll be able to reproduce it when it's finished although that might be tomorrow at this rate (104 updates).

**Comment by samclarke** [comment] 2017-09-09 19:36
The VM has finished updating but it's updated to version 11.0.9600.18762 which doesn't seem to crash for me.

Does using the editor on [sceditor.com](https://www.sceditor.com/) crash IE for you? If not do you have any custom BBCodes and does it still crash if you remove them? Or if it does crash on sceditor.com is it specific BBCode or any BBCode?

**Comment by rnilsen75** [comment] 2017-09-11 16:58
@samclarke, thanks for looking into this and also for fixing the grunt build. The version I have is 11.540.15063.0. What we ended up doing, that fixes the problem, is to initialize the sceditor in source mode, and then use a setTimeout switching it to WYSIWYG mode. It does not at explain why IE11 crashes like this. The next step would have been to try to debug IE11 itself, using Visual Studio. But that would take too much efforts, plus the "fix" seems to be working ok for us, even if a bit hackish. Just as a note, we do this for IE11 only, as it is the only effected browser.

**Comment by samclarke** [comment] 2017-09-30 17:12
Thanks @varora1406 and @rnilsen75 for reporting and the workaround.

I'm going to close this as I still can't reproduce this so I'm fairly sure it's specific to that version of IE 11 and/or there is something else interacting with SCE which is causing IE to crash. Either way it's an IE bug and as you have a workaround there isn't much else I can do. I could add your workaround to SCE by the time it's deployed most users will hopefully have already upgraded IE.

If anyone can reproduce this with a different version of IE please add a comment or create a new issue and I'll have another look.

**Closed by samclarke** 2017-09-30 17:12 UTC
Labels: Bug?, Cannot Reproduce, Needs Info
