### ISSUE TITLE
Starting with empty lines

### ISSUE THREAD

**Issue by Conver** [samclarke/SCEditor#559] opened 2017-02-27 17:02 UTC
When sceditor is not activated, then I can make empty starte lines in the textarea, but when activated it strips out the starting empty lines and goes right to the text.

Is there a workaround for this?

**Comment by samclarke** [comment] 2017-02-28 14:07
I've just tried and can't seem to reproduce this issue with either loading or setting with `val()`. Could you take a look and see what I'm doing differently: https://jsfiddle.net/xemcmpsm/2/

**Comment by Conver** [comment] 2017-02-28 15:53
Hmm.. I can see it's working on your end.. Wonder what Im doing wrong them.. 

I'll paste my version later today.

**Comment by samclarke** [comment] 2017-03-06 17:28
Closing as can't reproduce. Feel free to re-open or create another issue if you're able to reproduce the issue.

**Closed by samclarke** 2017-03-06 17:28 UTC
Labels: Cannot Reproduce
