### ISSUE TITLE
Bold tag used inside the code tag results in bolding

### ISSUE THREAD

**Issue by emanuele45** [samclarke/SCEditor#493] opened 2015-12-11 13:38 UTC
Funny one I think.
- Source mode.
- Type:

```
[code][b]something[/code]
something else
```
- Toggle to WYSIWYG mode
  => anything after the code block is bold.
- Toggle back to source mode
  => The bbcode has been changed to:

```
[code][b]something[/code]
[b]something else[/b]
```

The funny part is that apparently it happens only with the [b] tag, and not with [i], [u], [ul] or other tags.

Tested with the demo at http://www.sceditor.com/ that should be the latest version.

**Comment by brunoais** [comment] 2015-12-12 20:37
How should it have behaved?
On which browser (including the version) did you test that?

**Comment by emanuele45** [comment] 2015-12-13 21:59
I would expect that anything inside a [code] tag is threaded as... well, code and not be parsed in any way, in fact the same thing that happens using any other tag apart from [b]. So I'd expect the source remains exactly the same as inputed.

Browser appears not to be relevant.

**Comment by brunoais** [comment] 2015-12-13 22:00
I cannot reproduce it on mine.

**Comment by emanuele45** [comment] 2015-12-14 17:22
I can reproduce it, but I can't debug it. You could debug it, but you can't reproduce the behaviour.
I guess we can just forget about it until someone able to reproduce and debug it appears. ;)

**Comment by brunoais** [comment] 2015-12-15 06:47
You could start by telling me the browser you are using including the version. That is a good start... I may be able to reproduce it that way.

**Comment by emanuele45** [comment] 2016-04-23 16:49
Try with:
```
[code][b]something[/code]
[b]something else[/b]
```
and toggle.
I tested this one on:
* edge
* palemoon
* chrome
* opera (old 12.something)
and in all of them the result is wrapping the "something else" with an additional pair of b tags at each toggle.

**Comment by samclarke** [comment] 2017-03-08 13:02
Thanks for reporting! Should be fixed in V2.

**Closed** 2017-03-08 13:01 UTC
Labels: Bug
