### ISSUE TITLE
focus event also emit a blur event

### ISSUE THREAD

**Issue by hodshemtov** [samclarke/SCEditor#528] opened 2016-08-05 09:56 UTC
hi
I try to call some logic on focus and on blur and noticed that focus also emit a blur event.

is there a reason for this or its a bug?

thanks

**Comment by brunoais** [comment] 2016-08-05 11:09
Show me examples please.

**Comment by hodshemtov** [comment] 2016-08-05 12:16
please see common.js (line 326) at http://uat.experien.city/stationEditor/#/form?tpl=2

**Comment by brunoais** [comment] 2016-08-05 17:36
Show me examples of that happening please.

**Comment by hodshemtov** [comment] 2016-08-05 19:23
if you go to the link i sent, login and click inside/outside the sceditor you will see it in the devtools console

**Comment by brunoais** [comment] 2016-08-05 19:35
username and password for me please

**Comment by hodshemtov** [comment] 2016-08-05 19:50
test@test.test pswd: test

**Comment by brunoais** [comment] 2016-08-05 21:15
How can I replicate it?
I've tried focusing on it, then clicking on something else, then clicking it and typing some text, then clicking outside....
I've paid attention to the logs in the console and I didn't get `blur` followed by `Focus` or vice-versa.

**Comment by hodshemtov** [comment] 2016-08-05 21:29
i am just playing with click inside and outside the editor area and i see it recreated. how can i show you this?

**Comment by brunoais** [comment] 2016-08-05 21:55
https://github.com/TheTarkus/WebMCam/releases
Then just attach it into your comment.

**Comment by hodshemtov** [comment] 2016-08-05 22:47
the video is available here
https://drive.google.com/file/d/0BxqxrU9sY9CAa19VazlKUHR5eVE/view?usp=sharing

**Comment by brunoais** [comment] 2016-08-06 06:19
The link you gave me above does not belong to the video in that video. Please give me the link to that page.

**Comment by hodshemtov** [comment] 2016-08-06 08:13
http://uat.experien.city/stationEditor/#/form?staid=24841

**Comment by brunoais** [comment] 2016-08-06 14:58
Sounds like a bug with chrome only when dealing with multiple editors on the same page and when the user clicks outside the text that already exists in the input. The `focus` event happens but then `blur` happens probably due to a refocus made programatically.

**Comment by samclarke** [comment] 2016-12-07 17:18
I've tried to re-create the code as closely as I can: https://jsfiddle.net/kogn8sm2/ but so far I can't get it to reproduce the issue.

I've also tried an older version (1.4.2): https://jsfiddle.net/kogn8sm2/1/ but again no luck. So I'm not sure if this is a bug in SCEditor or if it's some kind of conflict with something else on that page.

**Comment by samclarke** [comment] 2017-03-10 13:44
Closing as cannot reproduce. Feel free to re-open or create a new issue if you're still getting the issue.

**Closed by samclarke** 2017-03-10 13:44 UTC
Labels: Needs Info
