### ISSUE TITLE
sceditor magnificPopup modal in not working

### ISSUE THREAD

**Issue by hyPerdarKness** [samclarke/SCEditor#724] opened 2018-12-25 17:19 UTC
hi,

sceditor, magnificPopup modal in not working

any ideas?

modal in not working;
![modal_in](https://user-images.githubusercontent.com/46135911/50425155-1a359280-0882-11e9-9cd8-a14828755d27.jpg)
not modal working;
![not_modal](https://user-images.githubusercontent.com/46135911/50425156-1a359280-0882-11e9-83dd-8290c4532629.jpg)
@samclarke

**Comment by brunoais** [comment] 2018-12-26 10:59
How does that modal thing lays out the HTML?
Does that modal thing make the editor "appear" with visibility hidden?
Does that "modal" thing make the editor appear with width 0?

**Comment by samclarke** [comment] 2021-10-10 22:54
Closing as needs info. I know quite a few modal libraries clone/move around nodes which interferes with the editor so it might be caused by that. If it is that it can be fixed by creating the editor after the modal is created.

**Closed by samclarke** 2021-10-10 22:54 UTC
Labels: Needs Info
