### ISSUE TITLE
$ is undefined

### ISSUE THREAD

**Issue by Globulopolis** [samclarke/SCEditor#488] opened 2015-11-08 14:24 UTC
Got this in

``` javascript
return function (name, params, createHtml) {
    var template = _templates[name];

    $.each(params, function (name, val) {
        template = template.replace(
            new RegExp('\\{' + name + '\\}', 'g'), val
        );
    });

    if (createHtml) {
        template = $(template);
    }

    return template;
};
```

Initial code

``` javascript
jQuery(document).ready(function($){
    $('textarea').sceditor();
});
```

**Comment by brunoais** [comment] 2015-11-08 15:31
Where is it undefined?

**Comment by Globulopolis** [comment] 2015-11-08 15:51
development\jquery.sceditor.js (also in minified).
Package downloaded from http://www.sceditor.com/latest.zip

**Comment by brunoais** [comment] 2015-11-08 16:46
OK... asking in a different way...
On which line of code it is reporting as having undefined?

**Comment by Globulopolis** [comment] 2015-11-08 17:28
@brunoais 7136 and 7143 lines

**Comment by brunoais** [comment] 2015-11-13 22:46
Please give me an url where that happens. I can't find anything that can show me as being the cause

**Comment by Globulopolis** [comment] 2015-11-13 22:52
@brunoais I can't because it is in local dev environment.

**Comment by brunoais** [comment] 2015-11-13 22:53
Try typing this in the browser console:
`$`
What happens?

**Comment by Globulopolis** [comment] 2015-11-14 00:31
This show me a list with suggestions, but after press 'Enter' key, say 'undefined'.
If I replace $ with jQuery in jquery.sceditor.js, it's solve the problem.

PS! Found source at https://github.com/samclarke/SCEditor/blob/master/src/lib/templates.js#L102 and https://github.com/samclarke/SCEditor/blob/master/src/lib/templates.js#L109

**Comment by brunoais** [comment] 2015-11-14 11:49
As a temp fix, please do not use jQuery's `.noConflit()` method, then try again.
I'll see why the guard from `jQuery` to `$` is not being added.

**Comment by jvextensions** [comment] 2016-05-14 13:10
I also have the same issue at the same line 
TypeError: $ is undefined

Is there a fix for this already? 

Thanks

**Comment by brunoais** [comment] 2016-05-14 18:18
@jvextensions are you using jQuery's `.noConflict()`?

**Comment by jvextensions** [comment] 2016-05-20 12:59
Yes I use Joomla and load jQuery in noConflict mode. But i have fixed this, by modifying the following lines in bbcode.js:

7136:
`$.each(params, function (name, val) { `
to 
`JQuery.each(params, function (name, val) {`

and in 7143:
`template = $(template);`
to
`template = jQuery(template);`

**Comment by brunoais** [comment] 2016-05-20 17:35
OK. Thanks for telling it.

**Closed** 2016-11-14 19:35 UTC
Labels: Bug
