### ISSUE TITLE
<style> tags gets wrapped in div

### ISSUE THREAD

**Issue by timint** [samclarke/SCEditor#482] opened 2015-09-21 22:19 UTC
Adding a style tag wrapps it in a div or p.

```
<p>
  <style> .class { rule: value; } </style>
</p>
```

What was expected to happen was:

```
<style> .class { rule: value; } </style>
```

**Comment by brunoais** [comment] 2015-09-22 06:37
As child or descendant of the `<body>` of the HTML?

**Comment by timint** [comment] 2015-09-22 15:07
As an immediate child. I tried opening fresh with a style tag right before any div content.

**Comment by timint** [comment] 2015-09-22 15:09
```
<style>
.class {
  rule: value;
}
</style>
<div><img ... /></div>
```

Becomes

```
<div>
  <style> .class { rule: value; } </style>
  <img ... />
</div>
```

**Comment by brunoais** [comment] 2015-09-22 15:20
Sam may have different ideas but I won't fix this.
The reason for it is that I don't believe that SCE should be prepared for invalid HTML.
About the `<style>` with the scoped attribute. That can be seen and checked-out at a different time.

**Comment by timint** [comment] 2015-09-22 15:23
I would understand a low priority but I am confused by how style is an invalid HTML element? Is script supported?

**Comment by brunoais** [comment] 2015-09-22 15:29
http://www.w3.org/TR/html5/document-metadata.html#the-style-element
> Contexts in which this element can be used:
Where metadata content is expected.
In a noscript element that is a child of a head element.

Nothing is done about the `<script>` tag as far as I remember. I do not know the xhtml plugin, though.

**Comment by timint** [comment] 2015-09-25 00:15
What is your opinion in the following?

This:
```
<style>
.box {
  rule: value;
}
</style>
<div class="box white">
```

Becomes:
```
<p> 
</p>
<p>
	<style>.box { rule: value; } </style>
</p>
<div class="box white">
```

**Comment by brunoais** [comment] 2015-09-25 06:36
Not a bug. Using invalid input produces unspecified output.
However, If using the scoped attribute it still does not detect, it becomes either a bug or a feature request, depending on the POV.

**Closed** 2015-11-08 15:40 UTC
Labels: WONTFIX
