### ISSUE TITLE
Is this project maintained or abandoned?

### ISSUE THREAD

**Issue by abetis** [samclarke/SCEditor#706] opened 2018-08-11 16:30 UTC
Hello,

I'd like to know if this project is maintained or was abandoned?

There is no activity by the author for pretty long time.
All I see is @brunoais and @q2apro activity in adding/responding to the issues...

Would like to know the status in order to decide whether I will spend more time trying to fix some very annoying (for me) bugs or switch to another solution.

Thanks.

**Comment by CyrilHskt** [comment] 2018-08-14 13:38
If you find another solution, could you tell me wich one ? Thx

**Comment by abetis** [comment] 2018-08-14 13:41
For now those are paying solutions, but since I need it for my business, I might consider that as well...
For now I'm the only user who enters the input using SCEditor, but when the time comes where I'll have to give other users accessing that input, I'll need a better solution than current SCEditor's shape...

**Comment by CyrilHskt** [comment] 2018-08-14 13:49
If you found another solution, even if it cost something, I'm interessted. I'm just fighting with Angular in order to implement this stuff. :-D

**Comment by abetis** [comment] 2018-08-14 14:28
https://www.tiny.cloud/
https://ckeditor.com/
There are many others...

**Comment by abetis** [comment] 2018-08-28 06:34
Before I've started using SCEditor, I've tried different free solutions, but that one was way better than any other.
SCEditor have great potential, and I use it for few months already, despite the bugs.
The most annoying bug for me is the multiple new lines entered when trying to delete something.
I did see something similar in GMail's interface, but that rarely happens there, probably a common problem, but Google found a solution for that.
I'm too busy with other things to look for the bug...

**Comment by brunoais** [comment] 2018-08-28 12:45
Unfortunately, the same on my side.

**Comment by FilipQL** [comment] 2018-08-28 13:32
@abetis I saw that you were working on some plugins such as:

- [alternative-lists.js](https://github.com/abetis/SCEditor/blob/master/src/plugins/alternative-lists.js)
- [list-enhanced.js](https://github.com/abetis/SCEditor/blob/master/src/plugins/list-enhanced.js)
- [percentage-fontsize.js](https://github.com/abetis/SCEditor/blob/master/src/plugins/percentage-fontsize.js)
- [video.js](https://github.com/abetis/SCEditor/blob/master/src/plugins/video.js)

https://github.com/abetis/SCEditor/tree/master/src/plugins

If I see it well, I think that's exactly what I need: 

- phpBB style of the lists:
```
 * [list]
 * [*]item
 * [*]item
 * [/list]
```
- Videos like this: 
```
[video=youtube]https://www.youtube.com/watch?v=vGc4mg5pul4[/video]
```

Do these plugins work, and can I use them?

**Comment by abetis** [comment] 2018-08-28 13:46
@FilipQL 
phpBB lists are in alternative-lists plugin.

For video I've used a separate tag for [youtube] and [facebook] since I used the parameter to specify the start of the video (in seconds), like [youtube=123] will start playing on 2:03 (minutes).

**Comment by FilipQL** [comment] 2018-08-28 17:19
@abetis 
I need [MyBB](https://github.com/mybb/mybb) _dialect_ because I'm using [MyBB's converter](https://github.com/mybb/mybb/blob/feature/inc/class_parser.php) (in my Laravel/PHP project... Of course, I had to make some small changes and adjustments in order to make it work with Laravel).

MyBB uses SCEditor - @samclarke created [SCEditor MyBB plugin](https://github.com/samclarke/SCEditor-MyBB) ~ five years ago, but it is still the MyBB's default BBCode editor (the latest MyBB release is v1.8.18. - it was released Aug 22, 2018, and it uses that old version of [SCEditor](https://github.com/samclarke/SCEditor-MyBB)).

Since I'm already using [MyBB's converter](https://github.com/mybb/mybb/blob/feature/inc/class_parser.php), I planned to simply use [MyBB's SCEditor](https://github.com/samclarke/SCEditor-MyBB) but the problem is that it requires some old version of jQuery and is simply not compatible with the project I'm currently working on (which uses Bootstrap 4 and some other plugins that require the latest version of jQuery) (and, also, it is not responsive).

The differences between the [MyBB's SCEditor](https://github.com/samclarke/SCEditor-MyBB) and the latest release of [SCEditor (v2.1.3)](https://github.com/samclarke/SCEditor) are:

- LISTS: 
```
[list]
[*]Item 1
[*]Item 2
[*]Item 3
[*]Item 4
[/list]
```
- VIDEO:
![1](https://user-images.githubusercontent.com/18264428/44738900-8e3f7400-aaf6-11e8-89b7-bfc1dbd80d5d.png)

```
[video=youtube]https://www.youtube.com/watch?v=vGc4mg5pul4[/video]
```
- FONT SIZE:
```
[size=large]text[/size]
```
- ALIGN:
```
[align=center]text[/align]
```
It looks like some of your plugins solve some of these problems :+1:  :)

**Comment by abetis** [comment] 2018-08-28 18:05
@FilipQL 
You'll probably have to add the rest by yourself :)

**Comment by FilipQL** [comment] 2018-08-28 20:53
At the moment, I'm focused on other things, but I will definitely have to work on that later (and I hope I will succeed :) ).

**Comment by xchwarze** [comment] 2020-01-24 05:26
CKEditor + Plugins = Size +1000k
SCEditor + Plugins = Size +100k

It is sad that the project dies because they do not put more people keeping it.
Put more users with permissions to merge pull requests so the project does not die.

**Comment by brunoais** [comment] 2020-01-24 07:09
If the project owner doesn't go extra mile to maintain it throughout the first years, how can someone else do?
That's the main issue here, unfortunately.

**Comment by abetis** [comment] 2020-01-24 07:26
Clone and maintain your own repository...

--
*א.ב. יזמות:*
www.4project.co.il - כל הרכיבים לפרוייקט שלכם
www.100dek.co.il - לא רק ציוד משרדי

**Comment by brunoais** [comment] 2020-01-24 09:07
No time myself and I mostly don't know this code... Even though I was given the "collaborator" badge

**Comment by abetis** [comment] 2020-01-24 09:22
So we can call it abandoned :)
I've cloned it and made changes that I needed for my usage...

--
*א.ב. יזמות:*
www.4project.co.il - כל הרכיבים לפרוייקט שלכם
www.100dek.co.il - לא רק ציוד משרדי

**Comment by brunoais** [comment] 2020-01-24 13:00
Maybe the guy is dead. He appeared once and there's 0 activity of him on github

**Comment by xchwarze** [comment] 2020-01-24 14:01
@brunoais Unfortunately you are the person with the most knowledge of the project.
You could clone it and merge the pull requests. Also announce that there are looking for more collaborators.

Maybe that way the project could be saved

**Comment by Doidel** [comment] 2021-04-08 04:20
Looks like a happy ending @samclarke :) Glad you're at it again!

**Comment by live627** [comment] 2021-04-08 06:44
Indeed . And now we can close this and look to the future.

**Closed by live627** 2021-04-08 06:44 UTC

**Comment by xchwarze** [comment] 2021-04-28 18:09
the future? We all deprecate the use of this plugin in our projects.
What assures me that the project will not be abandoned again?

**Comment by jdarwood007** [comment] 2021-04-29 01:16
The project is under the [MIT License](https://tldrlegal.com/license/mit-license), so technically anyone is free to fork it, fix code and distribute it on there own.

@samclarke has granted @live627 and some other Team members of @SimpleMachines rights to contribute code to SCEditor.  As our SMF project is using SCEditor, we do intend to keep it working for the foreseeable future.
