### ISSUE TITLE
Form unbinding error

### ISSUE THREAD

**Issue by ionalchemist** [samclarke/SCEditor#787] opened 2021-02-11 16:06 UTC
I came across an issue with unbinding the editor from the form submit event. Here is the relevant code:
![image](https://user-images.githubusercontent.com/3453401/107661826-7f08fe00-6c3e-11eb-85c5-ce67f9260c57.png)
![image](https://user-images.githubusercontent.com/3453401/107661923-99db7280-6c3e-11eb-9544-dfab08ee4de3.png)
The `on` function is passed `EVENT_CAPTURE = true`, but the `off` function does not pass `true`. In order for the unbinding to be successful via `removeEventListener`, it must be passed the same state for event capture as `addEventListener`.

The error resulted in the wrong value being submitted after calling `destroy()` on the loaded editor. No matter what I did after destroying the editor to manipulate the value, it would submit the editor's last known value instead.

Great editor btw!

**Comment by live627** [comment] 2021-02-13 00:51
Duplicate of #735

**Closed by live627** 2021-02-13 00:51 UTC
